### ISSUE TITLE
Fee behaviour

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-scenarios#10]
Add [fee](https://nemtech.github.io/concepts/transaction.html#fee) behaviour to [announce a transaction](https://github.com/nemtech/nem2-scenarios/blob/master/features/transaction/announce-a-transaction.feature) feature.

**Comment by SuheilMakrani** [comment]
i would like to work on this

**Comment by dgarcia360** [comment]
Perfect @SuheilMakrani, let me know if do you have any questions.

**Comment by SuheilMakrani** [comment]
Hey @dgarcia360 . I attempted to add the fee behavior but not sure that it's what you need.
`  Scenario: Alice announces a valid transaction
    Given Alice defined a valid transaction
    And she signed the transaction
    When Alice announces the transaction to a "MAIN_NET" 
    Then she should receive a confirmation message
    And is charged a fee which is a product of the size of transaction and fee multiplier set by the harvester`

**Comment by SuheilMakrani** [comment]
Hi @dgarcia360 . I have made a simple attempt to understand the fee behavior and not really sure how it works. 
This is my attempt
```
  Scenario: Alice announced a valid transaction
    Given Alice announced a valid transaction to the "MAIN_NET"
    When he transaction status is "Success"
    Then Alice's balance is the deducted by the <transactionfee>

```
Is this how it works?

**Comment by SuheilMakrani** [comment]
Hi @dgarcia360 i had some questions regarding the fee behavior
1. Do we need to show the fee behavior for a scenario where the transaction is expected to fail?
i did make an attempt on showing fee behavior for a scenario where we expect the scenario to fail
```   
Scenario: An account announced a transaction with an expired deadline
    Given Alice announced 3 hours ago a transaction with a deadline of 2 hours to the "MAIN_NET"
    When Alice announces the transaction to a "MAIN_NET" node
    And the transaction status is Failed due to error "Failure_Core_Past_Deadline"
    Then the "transaction_fee" will not be deducted from her "nem:xem" balance
```
2. Is this the correct way of showing the fee behaviour?
```
Scenario: An account announced a valid transaction
    Given Alice announced a valid transaction to the "MAIN_NET"
    When the transaction status is Success
    Then her "nem:xem" balance is the deducted by the "transaction_fee"
```

**Comment by dgarcia360** [comment]
Hi @SuheilMakrani,

> 1. Do we need to show the fee behavior for a scenario where the transaction is expected to fail?

Seems a good idea. I'd create new scenarios to validate fee behavior, not mixing it with the expired deadline scenario. Remember to define in the "Given" clause which is the "harvesting mosaic". 

Also, you could validate what happens if a transaction is not included because ``max_fee`` was too low, and the different inclusion strategies.

> 2. Is this the correct way of showing the fee behaviour?

There are some catapult concepts missing such as the maximum fee defined, the transaction's size, the node's fee_multiplier, or the harvesting mosaic. More info [Fee - Transaction](https://nemtech.github.io/concepts/transaction.html#fees).
