### ISSUE TITLE
Receipts behaviour

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-scenarios#9]
Add [receipts](https://nemtech.github.io/concepts/receipt.html#recorded-receipts) behaviour to each scenario.

**Comment by lowkaweiken** [comment]
Hmm I will take a look at this

**Comment by dgarcia360** [comment]
Perfect @lowkaweiken , let me know if do you have any questions.

**Comment by lowkaweiken** [comment]
I'm looking at the send-an-asset.feature file, not really sure about the proper way to do this.
```
  Scenario Outline: An account sends an asset to another account
    When "Alice" sends  <amount> "<asset>" to "Bob"
    Then "Alice" should receive a confirmation message
    And "Bob" should receive <amount> "<asset>"
    And her "<asset>" balance should decrease in <amount> unit(s)
    And "Alice" should get a Mosaic_Alias_Resolution and Mosaic_Levy receipt
```
Is this how it works?

**Comment by dgarcia360** [comment]
The scenario suggested refers to the receipts implementation and not to how are they used.  I would expect the test's developer to check that a receipt has been issued in the step ``And "Bob" should receive 1 "event.organizer"``.  

To write the validation scenarios for receipts, as we are just validating behavior,  we can ask ourselves: why do we need "Mosaic_Alias_Resolution" receipt?  Is the behavior going to be understood by business people and devs? 

What we want to know is the address for an aliased recipient given transaction.

```
    Scenario: An account wants to get the address of an aliased recipient for a given transaction
    Given "Ticket vendor" sent 1 "event.organizer" to "Bob"
    When "Ticket vendor" wants to get "Bob" address for this transaction
    Then "Ticket vendor" should get "SCVG35-ZSPMYP-L2POZQ-JGSVEG-RYOJ3V-BNIU3U-N2E6"
````

Do not hesitate to post more examples in case of doubt before making the PR 👍

**Comment by lowkaweiken** [comment]
Thanks @dgarcia360 for the reply! Forgive me if I did not understand your message clearly, but we have to write a whole new scenario specifically to demonstrate the receipt behavior, for any transactions that requires it?

Taking inspiration from your example above, I'm looking to describe the mosaic receipt behavior from your code in _send-an-asset.feature_

```
  Scenario Outline: An account sends an asset to another account
    When "Alice" sends  <amount> "<asset>" to "Bob"
    Then "Alice" should receive a confirmation message
    And "Bob" should receive <amount> "<asset>"
    And her "<asset>" balance should decrease in <amount> unit(s)
```
My understanding is that I should describe the receipt behavior at ```And "Bob" should receive <amount> "<asset>"```. So, below this section, I should write something like:

```
  Scenario: Alice wants to get the mosaic ID of an aliased mosaic for a given transaction
  Given "Alice" sent <amount> "event.organizer" to "Bob"
  When "Alice" wants to get "event.organizer" mosaic ID for this transaction
  Then "Alice" should get "0dc67fbe1cad29e5"
```
Thanks! I'm still trying to understand this whole thing 😂

**Comment by dgarcia360** [comment]
> we have to write a whole new scenario specifically to demonstrate the receipt behavior, for any transactions that requires it?

Yes, I would write a new scenario for each receipt, assuming that the transaction has already been confirmed.

> My understanding is that I should describe the receipt behavior at `And "Bob" should receive <amount> "<asset>"`. So, below this section, I should write something like:

Not necessarily under  `And "Bob" should receive <amount> "<asset>"`, you can add the new scenarios at the end of each file.
 
> ```
  Scenario: Alice wants to get the mosaic ID of an aliased mosaic for a given transaction
  Given "Alice" sent <amount> "event.organizer" to "Bob"
  When "Alice" wants to get "event.organizer" mosaic ID for this transaction
  Then "Alice" should get "0dc67fbe1cad29e5"
```

This scenario is valid 🙂

**Comment by lowkaweiken** [comment]
Hi @dgarcia360 , here are some samples that we did over the weekend. Do check it out:

### create_a_multisignature_contract.feature
```
  Scenario: Alice wants to get the state change of M-of-N multisig contract
    Given Alice published the multisig contract
    When Alice wants to get the state change of the multisig contract
    Then Alice should get the "confirmed" status of the multisig contract
```
### register_an_asset.feature
```
  Scenario: Alice wants to get her XEM balance after registering an expiring asset
    Given Alice registered an expiring asset for <seconds> seconds
    And she became the owner of the new expiring asset
    When Alice wants to get her xem balance after asset registration
    Then Alice should find her xem balance has decreased in <cost> units
```
### exchange-assets-across-different-blockchains.feature
```
  #LockSecret_Created
  Scenario: An Account wants to check their balance after locking an asset
    Given Alice locked an asset "alice.token" on to the blockchain
    And wants to check her balance after locking the asset
    When Alice checks her asset balance
    Then she should see asset balance is reduced by 10 units
```
### create_an_escrow_contract.feature
```
  Scenario: Alice wants to see if every sender participant recevied a notification after publishing contract
    Given Alice defined the following escrow :
      | sender | recipient | type          | data             |
      | Alice  | Bob       | send-an-asset | 1 concert.ticket |
      | Bob    | Alice     | send-an-asset | 20 euros         |
    And She locked 10 "xem" to guarantee that the contract will conclude in less than 2 days
    And She published the contract
    When "Alice" wants to see if every sender participant received the notification to accept the contract
    Then "Alice" should see every sender participant has received that notification
```
### prevent-receiving transactions-containing-a-specific-asset.feature
```
  # Transaction_Group receipt
  Scenario: Alice wants to get the state change of blocking transactions
    Given Alice blocks the receiving transactions containing specific assets
    When Alice wants to get the state change of the her blocking transaction
    Then Alice should get the "confirmed" status of the blocking transaction
```
### create_a_subnamespace
```
  Scenario: Alice wants to check her xem balance after creating a subnamespace
    Given Alice registered the namespace "one" for a week
    And she created a subnamespace named "one.two"
    When Alice wants to check her xem balance after creating namespace and subnamespace
    And She received a confirmation message
    And She became the owner of the subnamespace "one.two"
    Then She should see that her xem balance has decrease by 10 units
```
### announce-a-transaction.feature
```
# Transaction_Group receipt
  Scenario: Alice wants to get the state change of transaction
    Given Alice sends a valid transaction to the "MAIN_NET" node
    When Alice wants to get the state change of the her Transfer transaction
    Then Alice should get the "confirmed" status of the Transfer transaction
```
### send-a-message.feature
```
Scenario: Alice wants to see if recipient received her message
Given Alice sent "<message>" to "<recipient>"
And she received a confirmation message
When Alice wants to see if recipient received her message
And the "<recipient>" had received the message "<message>"
Then Alice should see that "<recipient>" has received "<message>"
```

**Comment by dgarcia360** [comment]
If you want to have a checklist of what is missing, check that there is one scenario per row listed in there:
https://nemtech.github.io/concepts/receipt.html#recorded-receipts
